### ISSUE TITLE
add color theme and design for pets page (CSS)

### ISSUE THREAD

**Issue by ckisi** [jjackson0228/Pawsitive-Connection#64]
https://colorhunt.co/palette/f3f3e0133e87608bc1cbdceb

these are the colors this link has the color names or hexvalue number just hover over the card

**Comment by jjackson0228** [comment]
https://colorhunt.co/palette/f3f3e0133e87608bc1cbdceb

these are the colors this link has the color names or hexvalue number just hover over the card
