### ISSUE TITLE
add color theme and design for profile page (CSS)

### ISSUE THREAD

**Issue by ckisi** [jjackson0228/Pawsitive-Connection#66]
add color theme we decided on  blue light blue tan and lighter blue 
![Screenshot 2024-11-05 at 9 33 02 PM](https://github.com/user-attachments/assets/164f45a9-80ee-4e8f-90e5-e44bac3ae1de)

**Comment by jjackson0228** [comment]
https://colorhunt.co/palette/f3f3e0133e87608bc1cbdceb
